"""Transform to restaurant tables

Revision ID: 0dd82ae65162
Revises: 6c3a5f61df0d
Create Date: 2026-04-09 13:51:47.638934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0dd82ae65162'
down_revision = '6c3a5f61df0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('restaurant_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_code', sa.String(length=40), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('guest_name', sa.String(length=255), nullable=True),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('guest_phone', sa.String(length=40), nullable=True),
    sa.Column('client_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('suggested_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('seating_preference', sa.String(length=120), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('session_option_id', sa.Integer(), nullable=True),
    sa.Column('terms_agreed_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['admin_accounts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client_accounts.id'], ),
    sa.ForeignKeyConstraint(['session_option_id'], ['session_options.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_code')
    )
    with op.batch_alter_table('restaurant_reservations', schema=None) as batch_op:
        batch_op.create_index('ix_restaurant_reservations_assigned_admin_id', ['assigned_admin_id'], unique=False)
        batch_op.create_index('ix_restaurant_reservations_client_id', ['client_id'], unique=False)
        batch_op.create_index('ix_restaurant_reservations_scheduled_start', ['scheduled_start'], unique=False)
        batch_op.create_index('ix_restaurant_reservations_status', ['status'], unique=False)

    op.create_table('reservation_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_client_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('note_text', sa.Text(), nullable=True),
    sa.Column('is_visible_to_client', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['restaurant_reservations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_admin_id'], ['admin_accounts.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_client_id'], ['client_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('receipt_url', sa.String(length=1024), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['restaurant_reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_drafts', schema=None) as batch_op:
        batch_op.drop_index('ix_booking_drafts_stripe_session_id')

    with op.batch_alter_table('gallery_items', schema=None) as batch_op:
        batch_op.drop_constraint('gallery_items_category_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'gallery_categories', ['category_id'], ['id'])

    op.drop_table('booking_drafts')
    op.drop_table('tattoo_categories')
    op.drop_table('appointment_payments')
    op.drop_table('appointment_assets')
    with op.batch_alter_table('tattoo_appointments', schema=None) as batch_op:
        batch_op.drop_index('ix_tattoo_appointments_assigned_admin_id')
        batch_op.drop_index('ix_tattoo_appointments_client_id')
        batch_op.drop_index('ix_tattoo_appointments_scheduled_start')
        batch_op.drop_index('ix_tattoo_appointments_status')

    op.drop_table('tattoo_appointments')

    with op.batch_alter_table('client_accounts', schema=None) as batch_op:
        batch_op.drop_constraint('client_accounts_email_key', type_='unique')
        batch_op.drop_index('ix_client_accounts_email')
        batch_op.create_index(batch_op.f('ix_client_accounts_email'), ['email'], unique=True)



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('gallery_items_category_id_fkey', 'tattoo_categories', ['category_id'], ['id'])

    with op.batch_alter_table('client_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_accounts_email'))
        batch_op.create_index('ix_client_accounts_email', ['email'], unique=False)
        batch_op.create_unique_constraint('client_accounts_email_key', ['email'], postgresql_nulls_not_distinct=False)

    op.create_table('appointment_assets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by_admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by_client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kind', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('note_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_visible_to_client', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['tattoo_appointments.id'], name='appointment_assets_appointment_id_fkey'),
    sa.ForeignKeyConstraint(['uploaded_by_admin_id'], ['admin_accounts.id'], name='appointment_assets_uploaded_by_admin_id_fkey'),
    sa.ForeignKeyConstraint(['uploaded_by_client_id'], ['client_accounts.id'], name='appointment_assets_uploaded_by_client_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='appointment_assets_pkey')
    )
    op.create_table('tattoo_appointments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tattoo_appointments_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('reference_code', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('contact_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('guest_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('guest_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('guest_phone', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('client_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('scheduled_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('suggested_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tattoo_placement', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('tattoo_size', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('placement_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('session_option_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('terms_agreed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('assigned_admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['admin_accounts.id'], name='tattoo_appointments_assigned_admin_id_fkey'),
    sa.ForeignKeyConstraint(['client_id'], ['client_accounts.id'], name='tattoo_appointments_client_id_fkey'),
    sa.ForeignKeyConstraint(['session_option_id'], ['session_options.id'], name='tattoo_appointments_session_option_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='tattoo_appointments_pkey'),
    sa.UniqueConstraint('reference_code', name='tattoo_appointments_reference_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('tattoo_appointments', schema=None) as batch_op:
        batch_op.create_index('ix_tattoo_appointments_status', ['status'], unique=False)
        batch_op.create_index('ix_tattoo_appointments_scheduled_start', ['scheduled_start'], unique=False)
        batch_op.create_index('ix_tattoo_appointments_client_id', ['client_id'], unique=False)
        batch_op.create_index('ix_tattoo_appointments_assigned_admin_id', ['assigned_admin_id'], unique=False)

    op.create_table('appointment_payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('provider_payment_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('amount_cents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('receipt_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['tattoo_appointments.id'], name='appointment_payments_appointment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='appointment_payments_pkey')
    )
    op.create_table('tattoo_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tattoo_categories_pkey'),
    sa.UniqueConstraint('name', name='tattoo_categories_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('booking_drafts',
    sa.Column('id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('stripe_session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('session_option_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scheduled_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inspiration_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pay_full_amount', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('amount_cents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('payment_note', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('fulfilled_appointment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fulfilled_appointment_id'], ['tattoo_appointments.id'], name='booking_drafts_fulfilled_appointment_id_fkey'),
    sa.ForeignKeyConstraint(['session_option_id'], ['session_options.id'], name='booking_drafts_session_option_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='booking_drafts_pkey')
    )
    with op.batch_alter_table('booking_drafts', schema=None) as batch_op:
        batch_op.create_index('ix_booking_drafts_stripe_session_id', ['stripe_session_id'], unique=True)

    op.drop_table('reservation_payments')
    op.drop_table('reservation_assets')
    with op.batch_alter_table('restaurant_reservations', schema=None) as batch_op:
        batch_op.drop_index('ix_restaurant_reservations_status')
        batch_op.drop_index('ix_restaurant_reservations_scheduled_start')
        batch_op.drop_index('ix_restaurant_reservations_client_id')
        batch_op.drop_index('ix_restaurant_reservations_assigned_admin_id')

    op.drop_table('restaurant_reservations')
    op.drop_table('gallery_categories')
    # ### end Alembic commands ###
