"""Add client_documents


Revision ID: 885455b76470
Revises: 5d2b5b5a28b1
Create Date: 2025-11-12 19:35:53.713530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885455b76470'
down_revision = '5d2b5b5a28b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment_payments', schema=None) as batch_op:
        batch_op.drop_index('ix_appointment_payments_appointment_id')
        batch_op.drop_constraint('appointment_payments_appointment_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tattoo_appointments', ['appointment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('appointment_payments_appointment_id_fkey', 'tattoo_appointments', ['appointment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('ix_appointment_payments_appointment_id', ['appointment_id'], unique=False)

    op.drop_table('client_documents')
    # ### end Alembic commands ###
